server:
  port: 8184
#  servlet:
#    context-path: /elastic-query-web-client
spring:
  thymeleaf:
    cache: false
    reactive:
      max-chunk-size: 8192
  webflux:
    base-path: /reactive-elastic-query-web-client
  codec:
    max-in-memory-size: 25MB


elastic-query-web-client:
  webclient:
    connect-timeout-ms: 10000
    read-timeout-ms: 10000
    write-timeout-ms: 10000
    max-in-memory-size: 10485760 # 10MB
    content-type: 'application/json'
    accept-type: 'text/event-stream'
    base-url: 'http://localhost:8183/reactive-elastic-query-service/documents'
  query-by-text:
    method: POST
    uri: "/get-doc-by-text"
    accept: ${elastic-query-web-client.webclient.accept-type}
#    service-id: elastic-query-service
#    instances:
#      -
#        id: elastic-query-service-1
#        host: localhost
#        port: 8183
#      -
#        id: elastic-query-service-2
#        host: localhost
#        port: 8185


#
#user-config:
#  username: test
#  password: 'test'
#  roles: USER