scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'grafana'
    scrape_interval: 1m
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3000']

  #  - job_name: 'kafka-streams-service'
  #    scrape_interval: 1m
  #    metrics_path: '/kafka-streams-service/actuator/prometheus'
  #    static_configs:
  #      - targets: ['host.docker.internal:8187']

  - job_name: 'analytics-service'
    scrape_interval: 1m
    metrics_path: '/analytics-service/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8188']

  - job_name: 'elastic-query-service-1'
    scrape_interval: 1m
    metrics_path: '/elastic-query-service/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8183']

#  - job_name: 'gateway-service'
#    scrape_interval: 1m
#    metrics_path: '/actuator/metrics'
#    static_configs:
#      - targets: ['gateway-service:9092']

#  - job_name: 'elastic-query-service-2'
#    scrape_interval: 1m
#    metrics_path: '/actuator/metrics'
#    static_configs:
#      - targets: [ 'elastic-query-service-2:8186' ]
